CREATE TABLE `#__pos_data_table_info` (
table_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
year YEAR DEFAULT 0,
x1_axis INT NULL,
x2_axis INT NULL,
round VARCHAR(100) NOT NULL,
yearly_change INT DEFAULT -1
) DEFAULT CHARSET=UTF8;

CREATE TABLE `#__pos_data_table` (
row_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
row_num INT NOT NULL,
data TEXT NULL,
x1_axis FLOAT NULL,
x2_axis FLOAT NULL,
table_id INT NOT NULL,
parent_id INT NULL,
is_header BOOLEAN,
yearly_change FLOAT NULL,
span VARCHAR(100) NOT NULL
) DEFAULT CHARSET=UTF8;